name: Deploy Flask App with Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: SERVER_HOST
    steps:
    # Проверяем код из репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Устанавливаем Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Копируем файлы на удаленный сервер и запускаем контейнеры
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}  # IP или домен вашего сервера
        username: ${{ secrets.SERVER_USER }}  # Пользователь для SSH
        password: ${{ secrets.SERVER_PASSWORD }}  # Пароль для SSH
        port: ${{ secrets.SERVER_PORT }}  # Порт SSH (по умолчанию 22)
        script: |
          # Переходим в директорию приложения
          cd book_store || exit
          # Обновляем репозиторий
          git pull origin master
          # Строим и запускаем контейнеры
          docker compose down
          docker compose up -d --build